/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author alumno
 */
public class PanelVisualizar extends javax.swing.JPanel {

    /**
     * Creates new form PanelVisualizar
     */
    public PanelVisualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        panelBotonesMovimiento = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();
        portadaImagen = new javax.swing.JLabel();
        changeImagePanel = new javax.swing.JPanel();
        changeImageButton = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        panelOtrasOpciones = new javax.swing.JPanel();
        panelRelleno = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldNifAutor = new javax.swing.JTextField();
        jLabelPropietario = new javax.swing.JLabel();
        jTextFieldPropietario = new javax.swing.JTextField();
        jLabelFechaPubli = new javax.swing.JLabel();
        jDatePickerFechaPubli = new org.jdatepicker.JDatePicker();

        setLayout(new java.awt.BorderLayout());

        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Listado de libros");
        add(tituloLabel, java.awt.BorderLayout.PAGE_START);

        panelBotonesMovimiento.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("jButton1");
        panelBotonesMovimiento.add(jButton1);

        jButton2.setText("jButton2");
        panelBotonesMovimiento.add(jButton2);

        add(panelBotonesMovimiento, java.awt.BorderLayout.SOUTH);

        panelImagen.setPreferredSize(new java.awt.Dimension(150, 260));
        panelImagen.setLayout(new java.awt.GridLayout(3, 1));
        panelImagen.add(portadaImagen);

        changeImageButton.setText("Cambiar imagen");

        javax.swing.GroupLayout changeImagePanelLayout = new javax.swing.GroupLayout(changeImagePanel);
        changeImagePanel.setLayout(changeImagePanelLayout);
        changeImagePanelLayout.setHorizontalGroup(
            changeImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(changeImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(changeImagePanelLayout.createSequentialGroup()
                    .addComponent(changeImageButton)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        changeImagePanelLayout.setVerticalGroup(
            changeImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(changeImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeImagePanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeImageButton)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        panelImagen.add(changeImagePanel);

        add(panelImagen, java.awt.BorderLayout.LINE_END);

        panelDatos.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelOtrasOpcionesLayout = new javax.swing.GroupLayout(panelOtrasOpciones);
        panelOtrasOpciones.setLayout(panelOtrasOpcionesLayout);
        panelOtrasOpcionesLayout.setHorizontalGroup(
            panelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        panelOtrasOpcionesLayout.setVerticalGroup(
            panelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        panelDatos.add(panelOtrasOpciones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelRellenoLayout = new javax.swing.GroupLayout(panelRelleno);
        panelRelleno.setLayout(panelRellenoLayout);
        panelRellenoLayout.setHorizontalGroup(
            panelRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        panelRellenoLayout.setVerticalGroup(
            panelRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        panelDatos.add(panelRelleno, java.awt.BorderLayout.PAGE_START);

        dataPanel.setLayout(new java.awt.GridLayout(6, 2));

        jLabelISBN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelISBN.setText("ISBN");
        dataPanel.add(jLabelISBN);

        jTextFieldISBN.setEditable(false);
        dataPanel.add(jTextFieldISBN);

        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Titulo");
        dataPanel.add(jLabelTitulo);

        jTextFieldTitulo.setEditable(false);
        dataPanel.add(jTextFieldTitulo);

        jLabelPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecio.setText("Precio");
        dataPanel.add(jLabelPrecio);

        jTextFieldPrecio.setEditable(false);
        dataPanel.add(jTextFieldPrecio);

        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutor.setText("Nif autor P.");
        dataPanel.add(jLabelAutor);

        jTextFieldNifAutor.setEditable(false);
        dataPanel.add(jTextFieldNifAutor);

        jLabelPropietario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPropietario.setText("Propietario");
        dataPanel.add(jLabelPropietario);

        jTextFieldPropietario.setEditable(false);
        dataPanel.add(jTextFieldPropietario);

        jLabelFechaPubli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaPubli.setText("Fecha publicación");
        dataPanel.add(jLabelFechaPubli);
        dataPanel.add(jDatePickerFechaPubli);

        panelDatos.add(dataPanel, java.awt.BorderLayout.CENTER);

        add(panelDatos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeImageButton;
    private javax.swing.JPanel changeImagePanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private org.jdatepicker.JDatePicker jDatePickerFechaPubli;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelFechaPubli;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPropietario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNifAutor;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPropietario;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JPanel panelBotonesMovimiento;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelOtrasOpciones;
    private javax.swing.JPanel panelRelleno;
    private javax.swing.JLabel portadaImagen;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
