/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Autor;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author hyperyor
 */
public class SeleccionarAutor extends javax.swing.JDialog {

    /**
     * Creates new form SeleccionarAutor
     */
    
    private VerParticipantes papa;
    private ArrayList<Autor> autoresDisponibles;
    
    public SeleccionarAutor(java.awt.Frame parent, boolean modal, ArrayList<Autor> disp, VerParticipantes padre) {
        super(parent, modal);
        initComponents();
        
        papa = padre;
        autoresDisponibles = disp;
        
        cargarDatos();
        
        //System.out.println("\nCreamos el seleccionar autor");
        
        setResizable(false);
        Dimension jDialogTamaño=this.getPreferredSize();
        Dimension jFrameTamaño=parent.getSize();
        Point corrdenadasJDialog=this.getLocation();
        this.setLocation((jFrameTamaño.width-jDialogTamaño.width)/2+corrdenadasJDialog.x, (jFrameTamaño.height-jDialogTamaño.height)/2+corrdenadasJDialog.y);
        this.setVisible(true);
               
    }
    
    private void cargarDatos()
    {
        
        String[] autores = new String[autoresDisponibles.size()];

        for (int i = 0; i < autoresDisponibles.size(); i++) {
            autores[i] = autoresDisponibles.get(i).toString();
        }

        listadoAutores.setListData(autores);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        tituloListado = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        cancellButton = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoAutores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de autor");

        tituloListado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloListado.setText("Listado de autores disponibles");
        panelTitulo.add(tituloListado);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        acceptButton.setText("Aceptar");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        panelBotones.add(acceptButton);

        cancellButton.setText("Cancelar");
        cancellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellButtonActionPerformed(evt);
            }
        });
        panelBotones.add(cancellButton);

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(listadoAutores);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancellButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        int indice = listadoAutores.getSelectedIndex();
        
        if(indice >= 0)
        {
            papa.insertarElemento(indice);
        }
        else
        {
            
            JOptionPane.showMessageDialog(null, 
                            "No se ha seleccionado a ningun autor", "Error", 
                            JOptionPane.WARNING_MESSAGE);
            
            
        }
        
        this.dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SeleccionarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SeleccionarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SeleccionarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SeleccionarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SeleccionarAutor dialog = new SeleccionarAutor(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancellButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listadoAutores;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel tituloListado;
    // End of variables declaration//GEN-END:variables
}
